### ISSUE TITLE
Plugin crashed a server.

### ISSUE THREAD

**Issue by aloyen** [ZetaMap/moreCommands#12]
I just installed the plugin of the latest build (v11), but after I put this plugin in the /config/mods directory, then my server crashes with the following error:

```
[07-24-2022 16:43:58] [I] 1 mods loaded.
[07-24-2022 16:43:58] [I] Server loaded. Type 'help' for help.
[07-24-2022 16:43:58] [E] java.lang.RuntimeException: Error loading mod moreCommands
        at mindustry.mod.Mods.contextRun(Mods.java:707)
        at mindustry.mod.Mods.lambda$eachClass$27(Mods.java:695)
        at arc.struct.Seq.each(Seq.java:192)
        at mindustry.mod.Mods.eachClass(Mods.java:695)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:74)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)
Caused by: java.lang.NoSuchFieldError: net
        at moreCommandsPlugin.init(moreCommandsPlugin.java:35)
        at mindustry.mod.Mods.lambda$eachClass$26(Mods.java:695)
        at mindustry.mod.Mods.contextRun(Mods.java:705)
        ... 6 more
``` 
Versions: 
[07-24-2022 16:51:39] [I] Version: Mindustry 7-pre-alpha official / build 135.2
[07-24-2022 16:51:39] [I] Java Version: 18.0.1.1

**Comment by ZetaMap** [comment]
Plugin is not available for v7 for now, i working on thé new update

**Comment by ZetaMap** [comment]
@aloyen

**Comment by ZetaMap** [comment]
Issue pending.... It will closes now.

**Comment by ZetaMap** [comment]
Issue pending.... It will closes now.
