### ISSUE TITLE
Problem with plugin moreCommands

### ISSUE THREAD

**Issue by rodas80** [ZetaMap/moreCommands#5]
Hi, please help me.

Version: 126.2

Don't work auto-pause.

Error:

 
[11-14-2021 09:13:41] [I] 1 mods loaded.
[11-14-2021 09:13:41] [I] Server loaded. Type 'help' for help.
[11-14-2021 09:13:42] [I] auto-pause: 0 player connected -> Game paused...
host
[11-14-2021 09:14:09] [I] Randomized next map to be Wasteland.
[11-14-2021 09:14:09] [I] Loading map...
[11-14-2021 09:14:09] [I] Map loaded.
[11-14-2021 09:14:10] [I] Opened a server on port 6567.
java.lang.NoSuchMethodError: java.lang.String.strip()Ljava/lang/String;
        at data.TempData.<init>(TempData.java:29)
    at data.TempData.putDefault(TempData.java:73)
        at moreCommandsPlugin.lambda$new$6(moreCommandsPlugin.java:104)
        at arc.Events.lambda$fire$2(Events.java:30)
        at arc.struct.Seq.each(Seq.java:200)
        at arc.Events.fire(Events.java:30)
        at arc.Events.fire(Events.java:25)
        at mindustry.core.NetServer.lambda$new$6(NetServer.java:254)
        at mindustry.net.Net.handleServerReceived(Net.java:277)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:118)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
[11-14-2021 09:14:14] [I] 123fsfd has connected. [YaHWqlE9Yr8AAAAANVhmrw==]
java.lang.RuntimeException: Failed to read remote method 'connectConfirm'!
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:146)
        at mindustry.core.NetServer.lambda$new$7(NetServer.java:261)
        at mindustry.net.Net.handleServerReceived(Net.java:277)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:118)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: java.lang.NullPointerException
        at moreCommandsPlugin.lambda$new$7(moreCommandsPlugin.java:119)
        at arc.Events.lambda$fire$2(Events.java:30)
        at arc.struct.Seq.each(Seq.java:200)
        at arc.Events.fire(Events.java:30)
        at arc.Events.fire(Events.java:25)
        at mindustry.core.NetServer.connectConfirm(NetServer.java:778)
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:144)
        ... 6 more
[11-14-2021 09:14:21] [I] auto-pause: 0 player connected -> Game paused...
[11-14-2021 09:14:21] [I] 123fsfd has disconnected. [YaHWqlE9Yr8AAAAANVhmrw==] (closed)

**Comment by ZetaMap** [comment]
What is the version of java? 
to watch this, type 'version' in the server shell

**Comment by rodas80** [comment]
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by ZetaMap** [comment]
Ok, the problem is with your version of java, you need a lastest version.  Look README.md, I made some modifications on how to download a recent version of java.

**Comment by rodas80** [comment]
Thanks, version 12 works!

**Comment by ZetaMap** [comment]
=)
